name: Deploy Astro Site

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub token

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Current directory, where the Dockerfile and project exist
          file: ./Dockerfile
          push: true
          tags: ulvihas/astroresume:latest  # Your Docker image tag

      # Step 5: Set up SSH key for server access
      - name: Set up SSH key for server access
        run: |
          echo "Step 5: Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/vultr  # Remove carriage returns
          chmod 600 ~/.ssh/vultr
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/vultr
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  # Avoid SSH prompts
          echo "Step 5 completed."

      # Step 6: Debug SSH Setup (Check if SSH key exists)
      - name: Debug SSH Key File
        run: |
          echo "Step 6: Checking SSH key file..."
          ls -lah ~/.ssh || echo "No SSH files found!"
          cat ~/.ssh/vultr || echo "SSH private key file missing!"
          echo "Step 6 completed."

      # Step 7: Check if SSH key is loaded
      - name: Debug SSH Key Loaded
        run: |
          echo "Step 7: Checking if SSH key is loaded..."
          ssh-add -l || echo "SSH key not loaded!"
          echo "Step 7 completed."

      # Step 8: Test SSH Connection to Server
      - name: Debug SSH Connection
        run: |
          echo "Step 8: Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vultr root@${{ secrets.SERVER_IP }} -v || echo "SSH connection failed!"
          echo "Step 8 completed."

      # Step 9: Ensure SSH agent is running properly
      - name: Debug SSH Agent
        run: |
          echo "Step 9: Checking SSH agent..."
          ps aux | grep ssh-agent || echo "SSH agent is not running!"
          echo "Step 9 completed."

      # Step 10: Final SSH Verification Before Deployment
      - name: Final SSH Check Before Deployment
        run: |
          echo "Step 10: Final SSH verification..."
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/vultr root@${{ secrets.SERVER_IP }} || echo "Final SSH connection failed!"
          echo "Step 10 completed."

      # Step 11: SSH into the server and deploy the Docker container
      - name: Deploy to server via SSH
        run: |
          echo "Step 11: Deploying application..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vultr root@${{ secrets.SERVER_IP }} << 'EOF'
            echo "Connected to server. Starting deployment..."
            docker pull ulvihas/astroresume:latest
            docker stop astro-container || true
            docker rm astro-container || true
            docker run -d --name astro-container -p 80:80 ulvihas/astroresume:latest
            echo "Deployment complete!"
          EOF
          echo "Step 11 completed."
