name: Deploy Astro Site

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub token

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Current directory, where the Dockerfile and project exist
          file: ./Dockerfile
          push: true
          tags: ulvihas/astroresume:latest  # Your Docker image tag

      # Step 5: Set up SSH key for server access (Added More Debugging)
      - name: Set up SSH key for server access
        run: |
          set -e  # Exit if any command fails

          echo "Step 5: Setting up SSH key..."
          mkdir -p ~/.ssh
          
          echo "Step 5.1: Checking if ~/.ssh exists..."
          ls -lah ~/.ssh || echo "No ~/.ssh directory found!"
          
          echo "Step 5.2: Writing SSH key to file..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/vultr
          
          echo "Step 5.3: Checking if SSH key file exists..."
          ls -lah ~/.ssh/vultr || echo "SSH key file missing!"
          
          echo "Step 5.4: Setting file permissions..."
          chmod 600 ~/.ssh/vultr
          
          echo "Step 5.5: Verifying permissions..."
          ls -lah ~/.ssh/vultr
          
          echo "Step 5.6: Starting SSH agent..."
          eval "$(ssh-agent -s)"
          
          echo "Step 5.7: Adding SSH key to agent..."
          ssh-add ~/.ssh/vultr || echo "Failed to add SSH key!"
          
          echo "Step 5.8: Listing added SSH keys..."
          ssh-add -l || echo "No keys found in SSH agent!"
          
          echo "Step 5.9: Adding server to known hosts..."
          ssh-keyscan -H "104.238.158.154" >> ~/.ssh/known_hosts || echo "Failed to add known hosts!"
          
          echo "Step 5 completed successfully."

      # Step 6: Testing Network Connectivity
      - name: Test Network Connectivity from CI/CD Runner
        run: |
          echo "Step 6: Testing Network Connectivity from CI/CD Runner..."

          # Define the actual IP
          YOUR_SERVER_IP="104.238.158.154"
          
          # Display the current system IP to verify the server’s address
          echo "Server's IP Address:"
          curl -s ifconfig.me
          
          # Pinging the server to check if it is reachable
          echo "Pinging the server to check if it's reachable..."
          ping -c 4 $YOUR_SERVER_IP || echo "Unable to ping the server!"
          
          # Test network connectivity to port 22 using nc (netcat)
          echo "Testing TCP connection on port 22..."
          nc -zv $YOUR_SERVER_IP 22 || echo "CI/CD runner cannot reach the server on port 22!"
          
          # Check if the server is listening on port 22 (SSH)
          echo "Checking if the server is listening on port 22..."
          nc -zv localhost 22 || echo "The server is not listening on port 22 locally!"
          
          # Display routing table to check if there are any routing issues
          echo "Checking the routing table on the CI/CD runner..."
          route -n || echo "Unable to fetch the routing table!"
          
          # Check if there are any firewall rules that could be blocking connections
          echo "Displaying the firewall rules on the server..."
          sudo iptables -L || echo "Unable to fetch iptables rules!"
          
          echo "Step 6 completed. Please review the above information for further diagnostics."


      # Step 7: Debug SSH Connection Before Proceeding
      - name: Debug SSH Connection
        run: |
          echo "Step 7: Testing SSH connection..."
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/vultr root@104.238.158.154 || echo "SSH connection failed!"
          echo "Step 7 completed."

      # Step 8: Deploy to server via SSH
      - name: Deploy to server via SSH
        run: |
          echo "Step 8: Deploying application..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vultr root@104.238.158.154 << 'EOF'
            echo "Connected to server. Starting deployment..."
            docker pull ulvihas/astroresume:latest
            docker stop astro-container || true
            docker rm astro-container || true
            docker run -d --name astro-container -p 80:80 ulvihas/astroresume:latest
            echo "Deployment complete!"
          EOF
          echo "Step 8 completed."
